name: Deploy Containers

on:
  push:
    branches: [main]

jobs:
  login-build-push:
    name: Build, Push and Run
    runs-on: ubuntu-latest

    env:
      REGION: us-central1                   
      PROJECT_ID: my-mlflow-server           
      REPOSITORY: mlflow-containers          
      SERVICE_ACCOUNT: mlflow-sa             

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with: 
        project_id: '${{ env.PROJECT_ID }}'
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
    
    - name: 'Docker config'
      run: |-
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.6'

    - name: Install dependencies
      run: make install

    - name: Run code review (black, pylint, pytest)
      run: make code-review

    - name: 'Build FastAPI container'
      run: |-
        docker build -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/fastapi:${{ github.sha }}" -f Dockerfile .
      
    - name: 'Push FastAPI container'
      run: |-
        docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/fastapi:${{ github.sha }}"
    
    - name: Deploy FastAPI Server
      run: |
        gcloud run deploy "titanic-api" \
          --image "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/fastapi:${{ github.sha }}" \
          --region "${{ env.REGION }}" \
          --service-account "${{ env.SERVICE_ACCOUNT }}" \
          --memory 1Gi \
          --allow-unauthenticated \
          --port 8000
